/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "极简UI",
  "description": "一个好用的UI框架",
  "base": "/gulu/",
  "headTags": [],
  "pages": [
    {
      "title": "极简UI官网",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6a317ff4",
      "path": "/"
    },
    {
      "title": "按钮",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": "：",
        "6": "b",
        "7": "u",
        "8": "t",
        "9": "t",
        "10": "o",
        "11": "n",
        "12": " ",
        "13": "s",
        "14": "i",
        "15": "d",
        "16": "e",
        "17": "b",
        "18": "a",
        "19": "r",
        "20": "D",
        "21": "e",
        "22": "p",
        "23": "t",
        "24": "h",
        "25": ":",
        "26": "2"
      },
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-535973f4",
      "path": "/components/button.html"
    },
    {
      "title": "开始",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": "：",
        "6": "开",
        "7": "始"
      },
      "regularPath": "/get-started/",
      "relativePath": "get-started/README.md",
      "key": "v-7d53a76b",
      "path": "/get-started/"
    },
    {
      "title": "安装",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "安",
        "7": "装"
      },
      "regularPath": "/install/",
      "relativePath": "install/README.md",
      "key": "v-6d0c05c9",
      "path": "/install/"
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "入门",
        "collapsable": false,
        "children": [
          "/install/",
          "/get-started/"
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "children": [
          "/components/button"
        ]
      }
    ]
  }
}